name: Windows Build

on:
  [push, workflow_dispatch]
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: microsoft/setup-msbuild@v1
    - uses: ilammy/setup-nasm@v1
    - uses: ashutoshvarma/setup-ninja@master
    - uses: actions/checkout@v2

    - name: Setup Rust
      run: |
        rustup default stable-x86_64-pc-windows-msvc
        rustc -vV
        cargo -vV
    - name: Get submodules
      run: git submodule update --init --recursive
    - name: Build aom
      run: |
        cd ext
        git clone -b v3.0.0 --depth 1 https://aomedia.googlesource.com/aom
        cd aom
        mkdir build.libavif
        cd build.libavif
        cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DENABLE_DOCS=0 -DENABLE_EXAMPLES=0 -DENABLE_TESTDATA=0 -DENABLE_TESTS=0 -DENABLE_TOOLS=0 ..
        ninja
        cd ../..
    - name: Build libraries
      run: |
        cd ext
        #.\dav1d.cmd
        #.\rav1e.cmd
        .\libjpeg.cmd
        .\zlibpng.cmd
        cd ..
    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake --version
        cmake .. -DAVIF_CODEC_AOM=ON -DAVIF_LOCAL_AOM=ON -DAVIF_CODEC_DAV1D=ON -DAVIF_LOCAL_DAV1D=OFF -DAVIF_CODEC_RAV1E=OFF -DAVIF_LOCAL_RAV1E=ON -DBUILD_SHARED_LIBS=ON -DAVIF_LOCAL_JPEG=1 -DAVIF_LOCAL_ZLIBPNG=1 -DAVIF_BUILD_APPS=ON
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration="Release|x64" build\libavif.sln
    - uses: actions/upload-artifact@v2
      with:
         name: build
         path: build/Release
    - uses: actions/upload-artifact@v2
      with:
         name: log
         path: |
           build/**/*.log
           build/**/*.txt
