name: Windows Build

on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: ilammy/setup-nasm@v1
    - uses: seanmiddleditch/gha-setup-ninja@master
    #- name: Setup Visual Studio 2019
    #  run: |
    #    cmd.exe /c "call `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat`" && set > %temp%\vcvars.txt"
    #    Get-Content "$env:temp\vcvars.txt" | Foreach-Object {
    #      if ($_ -match "^(.*?)=(.*)$") {
    #        $key=$matches[1].ToString()
    #        $value=$matches[2].ToString()
    #        echo "$key=$value" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
    #      }
    #    }
    - name: Setup Rust
      run: |
        rustup default stable-x86_64-pc-windows-msvc
        rustc -vV
        cargo -vV
    - name: Check
      run: |
        $env:path
        ninja --version
        nasm --version
    - name: Get submodules
      run: git submodule update --init --recursive
    - name: Build libraries
      run: |
        cd ext
        .\aom.cmd
        #.\dav1d.cmd
        .\rav1e.cmd
        .\libgav1.cmd
        .\svt.cmd
        .\libjpeg.cmd
        .\zlibpng.cmd
        cd ..
    - name: Build libvyuv
      run: |
        cd ext
        git clone --single-branch https://chromium.googlesource.com/libyuv/libyuv
        cd libyuv
        git checkout 2871589
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" -DBUILD_SHARED_LIBS=0 -DCMAKE_BUILD_TYPE=Release ..
        msbuild /m /p:Configuration="Release" YUV.sln
        cd ../..
    - name: Build (static lib / app)
      run: |
        mkdir build
        cd build
        cmake --version
        cmake .. `
          -DAVIF_CODEC_AOM=ON `
          -DAVIF_LOCAL_AOM=ON `
          -DAVIF_CODEC_DAV1D=OFF `
          -DAVIF_LOCAL_DAV1D=ON `
          -DAVIF_CODEC_RAV1E=ON `
          -DAVIF_LOCAL_RAV1E=ON `
          -DAVIF_CODEC_LIBGAV1=ON `
          -DAVIF_LOCAL_LIBGAV1=ON `
          -DAVIF_CODEC_SVT=ON `
          -DAVIF_LOCAL_SVT=ON `
          -DAVIF_LOCAL_YUV=1 `
          -DAVIF_LOCAL_JPEG=1 `
          -DAVIF_LOCAL_ZLIBPNG=1 `
          -DBUILD_SHARED_LIBS=OFF `
          -DAVIF_BUILD_APPS=ON
        msbuild /m /p:Configuration="Release" libavif.sln
    - name: Build (shared lib)
      run: |
        mkdir build-dll
        cd build-dll
        cmake --version
        cmake .. `
          -DAVIF_CODEC_AOM=ON `
          -DAVIF_LOCAL_AOM=ON `
          -DAVIF_CODEC_DAV1D=OFF `
          -DAVIF_LOCAL_DAV1D=ON `
          -DAVIF_CODEC_RAV1E=ON `
          -DAVIF_LOCAL_RAV1E=ON `
          -DAVIF_CODEC_LIBGAV1=ON `
          -DAVIF_LOCAL_LIBGAV1=ON `
          -DAVIF_CODEC_SVT=ON `
          -DAVIF_LOCAL_SVT=ON `
          -DAVIF_LOCAL_YUV=1 `
          -DAVIF_LOCAL_JPEG=1 `
          -DAVIF_LOCAL_ZLIBPNG=1 `
          -DBUILD_SHARED_LIBS=ON `
          -DAVIF_BUILD_APPS=OFF
        msbuild /m /p:Configuration="Release" libavif.sln
    - uses: actions/upload-artifact@v2
      with:
         name: build
         path: |
           build/Release
           build-dll/Release
